### ISSUE TITLE
ImportError: cannot import name 'build_endpoint_description_strings'

### ISSUE THREAD

**Issue by littleant1111** [xianfuxing/django-tail#2]
出现这个是pip 安装版本不兼容导致，我测试了下，用如下组件可以运行成功：
Django==1.11.2
daphne==1.4.2
asgi-redis==1.4.0
asgiref==1.1.2
channels==1.1.3

**Comment by xianfuxing** [comment]
嗯，这个项目很久没更新了。现在channels已经2.2了。支持async def用法。有兴趣可以研究下。
